print("PROGRAMMER:", "John Paul C. Nieto")
print("DATE CREATED:","July 6: 2023")
print("DESCRIPTION OF THE PROGRAM:","This Program is for Practice/Testing")
print("FIRST NAME:", "John Paul")
print("MIDDLE NAME:", "Cajucom")
print("LAST NAME:", "NIETO")
print("COURSE:", "BSIT")
print("YEAR:", "3rd Year")
print("AGE:", "20")
print("GENDER:", "Male")
print("CIVIL STATUS:", "SINGLE")
print("NATIONALITY:", "FILIPINO" )
print("MOTTO:", "One Person Can Make a Difference")
print("SCHOOL:" , "PHINMA ARAULLO UNIVERSITY")
print("COLLEGE:", "CITE")
